### ISSUE TITLE
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 2 column 14 path $.userId

### ISSUE THREAD

**Issue by ubaid4j** [BeezUP/api-java-client#1]
### System
- Java version:  java 14 2020-03-17
- IDE: IntelliJ IDEA 2020.1.1 (Ultimate Edition)
- OS: Ubuntu 20.04 LTS

### How to generate
I wrote the following code to test against my API-Key. 
```
ApiClient defaultClient = Configuration.getDefaultApiClient();
ApiKeyAuth api_key = (ApiKeyAuth) defaultClient.getAuthentication("api_key");
api_key.setApiKey("my-own-api-key");
BeezUPApi apiInstance = new BeezUPApi();
try {
	AccountInfo result = apiInstance.getUserAccountInfo();
	System.out.println(result);
} catch (ApiException e) {
	System.err.println("Exception when calling BeezUPApi#getUserAccountInfo");
	e.printStackTrace();
}
	
```
then It throw the following error:
### Stack Trace
```
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 2 column 14 path $.userId

	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:226)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
	at com.google.gson.Gson.fromJson(Gson.java:932)
	at com.google.gson.Gson.fromJson(Gson.java:897)
	at com.google.gson.Gson.fromJson(Gson.java:846)
	at io.swagger.client.JSON.deserialize(JSON.java:103)
	at io.swagger.client.ApiClient.deserialize(ApiClient.java:840)
	at io.swagger.client.ApiClient.handleResponse(ApiClient.java:1036)
	at io.swagger.client.ApiClient.execute(ApiClient.java:970)
	at io.swagger.client.api.BeezUPApi.getUserAccountInfoWithHttpInfo(BeezUPApi.java:13651)
	at io.swagger.client.api.BeezUPApi.getUserAccountInfo(BeezUPApi.java:13638)
	at com.code.ubaid.beezupAPIService.BeezupApiServiceApplicationTests.contextLoads(BeezupApiServiceApplicationTests.java:33)
```
### Notes
I have deeply debugged it. Response is coming from the API but binding failed at this line 
```
            } else {
                return gson.fromJson(body, returnType);
            }
        } catch (JsonParseException e) {
```
of following code
```
    package io.swagger.client;
    ...
    ...
    ...
    ...

    /**
     * Deserialize the given JSON string to Java object.
     *
     * @param <T> Type
     * @param body The JSON string
     * @param returnType The type to deserialize into
     * @return The deserialized Java object
     */
    @SuppressWarnings("unchecked")
    public <T> T deserialize(String body, Type returnType) {
        try {
            if (apiClient.isLenientOnJson()) {
                JsonReader jsonReader = new JsonReader(new StringReader(body));
                // see https://google-gson.googlecode.com/svn/trunk/gson/docs/javadocs/com/google/gson/stream/JsonReader.html#setLenient(boolean)
                jsonReader.setLenient(true);
                return gson.fromJson(jsonReader, returnType);
            } else {
                return gson.fromJson(body, returnType);
            }
        } catch (JsonParseException e) {
            // Fallback processing when failed to parse JSON form response body:
            //   return the response body string directly for the String return type;
            //   parse response body into date or datetime for the Date return type.
            if (returnType.equals(String.class))
                return (T) body;
            else if (returnType.equals(Date.class))
                return (T) apiClient.parseDateOrDatetime(body);
            else throw(e);
        }
    }
}

```

**Comment by ubaid4j** [comment]
Its Obsolete
